server:
  port: 8081

spring:
  application:
    name: demo

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            # ğŸ‘‰ ç¡®ä¿è¿™é‡Œæ˜¯ 8081
            entity-id: "http://localhost:8081/saml2/service-provider-metadata/keycloak"
            signing:
              credentials:
                - private-key-location: "classpath:sp-private.key"
                  certificate-location: "classpath:sp-certificate.crt"
            assertingparty:
              # ğŸ‘‰ å…³é”®ç‚¹ï¼šè¿™é‡Œæ”¹ä¸º saml-test (å…¨å°å†™)ï¼Œä¸ä½ æµè§ˆå™¨çœ‹åˆ°çš„ XML è·¯å¾„ä¸€è‡´
              metadata-uri: "http://localhost:8080/auth/realms/saml-test/protocol/saml/descriptor"